name: Feature Request
description: >-
  ✨ Got a feature suggestion for something we can implement to make the project
  better?
title: '[FEATURE]: '
body:
  - type: markdown
    attributes:
      value: >-
        I'm always looking for ways to improve the project, so if you've got any
        feature suggestions at all, I'd love to hear them! If possible, could
        you make sure your suggestion is possible to build, and if you have any
        links or ideas how it might be implemented that's really help!
  - type: textarea
    id: suggestion
    attributes:
      label: Feature Suggestion
      description: Please explain your feature suggestion
    validations:
      required: true
  - type: dropdown
    id: worky
    attributes:
      label: Would you be up for working on this?
      options:
        - 'No'
        - Maybe
        - Yes, but with support
        - Hell yeah!
  - type: checkboxes
    id: confirmation
    attributes:
      label: Pre-Submission Checklist
      options:
        - label: I have checked this issue has [not already been raised](https://github.com/Lissy93/git-into-open-source/issues?q=is%3Aissue)
          required: true
        - label: I've searched the [docs](https://github.com/Lissy93/git-into-open-source/tree/main/.github) for an answer
          required: true
        - label: I agree to follow thr [Code of Conduct](https://github.com/Lissy93/git-into-open-source/blob/main/.github/CODE_OF_CONDUCT.md)
          required: true
  - type: markdown
    attributes:
      value: >-
        ![thanks](https://raw.githubusercontent.com/Lissy93/git-into-open-source/main/web/public/favicon.png)
        Thank you for taking the time to complete this ticket!
        You should receive a response within 48 hours :)
