name: Question
description: 🤔 Got a question, or something you need help with?
title: '[QUESTION]: '
body:
  - type: markdown
    attributes:
      value: >
        We've now opened up
        [Discussions](https://github.com/Lissy93/git-into-open-source/discussions),
        so for more general queries, or those not aimed specifically at the repo
        author, you might be better off posting there instead.
  - type: textarea
    id: question-body
    attributes:
      label: Question
      description: Go ahead, ask us anything!
  - type: checkboxes
    id: confirmation
    attributes:
      label: Pre-Submission Checklist
      options:
        - label: I have checked this issue has [not already been raised](https://github.com/Lissy93/git-into-open-source/issues?q=is%3Aissue)
          required: true
        - label: I've searched the [docs](https://github.com/Lissy93/git-into-open-source/tree/main/.github) for an answer
          required: true
        - label: I agree to follow the [Code of Conduct](https://github.com/Lissy93/git-into-open-source/blob/main/.github/CODE_OF_CONDUCT.md)
          required: true
  - type: markdown
    attributes:
      value: >-
        ![thanks](https://raw.githubusercontent.com/Lissy93/git-into-open-source/main/web/public/favicon.png)
        Thank you for taking the time to complete this ticket!
        You should receive a response within 48 hours :)
