
export const repoTags = [
  'first-timers-only',
  // 'hacktoberfest',
  // 'good-first-issue',
  // 'your-first-pr',
  'up-for-grabs',
];

export const languages = [
  {
    identifier: 'javascript',
    name: 'JavaScript',
    color: '#F7DF1E',
    icon: 'simple-icons:javascript',
  },
  {
    identifier: 'typescript',
    name: 'TypeScript',
    color: '#3178C6',
    icon: 'simple-icons:typescript',
  },
  {
    identifier: 'python',
    name: 'Python',
    color: '#3776AB',
    icon: 'simple-icons:python',
  },
  {
    identifier: 'go',
    name: 'Go Lang',
    color: '#00ADD8',
    icon: 'simple-icons:go',
  },
  {
    identifier: 'rust',
    name: 'Rust',
    color: '#000000',
    icon: 'simple-icons:rust',
  },
  {
    identifier: 'dart',
    name: 'Dart',
    color: '#0175C2',
    icon: 'simple-icons:dart',
  },
  {
    identifier: 'php',
    name: 'PHP',
    color: '#777BB4',
    icon: 'simple-icons:php',
  },
  {
    identifier: 'swift',
    name: 'Swift',
    color: '#FA7343',
    icon: 'simple-icons:swift',
  },
  {
    identifier: 'ruby',
    name: 'Ruby',
    color: '#CC342D',
    icon: 'simple-icons:ruby',
  },
  {
    identifier: 'kotlin',
    name: 'Kotlin',
    color: '#7F52FF',
    icon: 'simple-icons:kotlin',
  },
  {
    identifier: 'java',
    name: 'Java',
    color: '#007396',
    icon: 'bxl:java',
  },
  {
    identifier: 'c',
    name: 'C',
    color: '#A8B9CC',
    icon: 'simple-icons:c',
  },
  {
    identifier: 'csharp',
    name: 'C#',
    color: '#239120',
    icon: 'simple-icons:csharp',
  },
  {
    identifier: 'scala',
    name: 'Scala',
    color: '#DC322F',
    icon: 'simple-icons:scala',
  },
  {
    identifier: 'r',
    name: 'R',
    color: '#198CE7',
    icon: 'simple-icons:r',
  },
  {
    identifier: 'perl',
    name: 'Perl',
    color: '#39457E',
    icon: 'simple-icons:perl',
  },
  {
    identifier: 'vue',
    name: 'Vue.js',
    color: '#4FC08D',
    icon: 'simple-icons:vuedotjs',
  },
  {
    identifier: 'svelte',
    name: 'Svelte',
    color: '#FF3E00',
    icon: 'simple-icons:svelte',
  },
  {
    identifier: 'astro',
    name: 'Astro',
    color: '#BC52EE',
    icon: 'simple-icons:astro',
  },
  {
    identifier: 'zig',
    name: 'Zig',
    color: '#EC5500',
    icon: 'simple-icons:zig',
  },
  // {
  //   identifier: 'elm',
  //   name: 'Elm',
  //   color: '#60B5CC',
  //   icon: 'simple-icons:elm',
  // },
  // {
  //   identifier: 'shell',
  //   name: 'Shell',
  //   color: '#4EAA25',
  //   icon: 'simple-icons:gnubash',
  // },
  // {
  //   identifier: 'objective-c',
  //   name: 'Objective-C',
  //   color: '#438EFF',
  //   icon: 'vscode-icons:file-type-objectivec',
  // },
  // {
  //   identifier: 'vlang',
  //   name: 'V',
  //   color: '#4F87C4',
  //   icon: 'simple-icons:v',
  // },
  // {
  //   identifier: 'lua',
  //   name: 'Lua',
  //   color: '#000080',
  //   icon: 'simple-icons:lua',
  // },
  // {
  //   identifier: 'haskell',
  //   name: 'Haskell',
  //   color: '#5D4F85',
  //   icon: 'simple-icons:haskell',
  // },
  // {
  //   identifier: 'groovy',
  //   name: 'Groovy',
  //   color: '#4298B8',
  //   icon: 'simple-icons:apachegroovy',
  // },
  // {
  //   identifier: 'elixir',
  //   name: 'Elixir',
  //   color: '#4B275F',
  //   icon: 'simple-icons:elixir',
  // },
  // {
  //   identifier: 'clojure',
  //   name: 'Clojure',
  //   color: '#5881D8',
  //   icon: 'simple-icons:clojure',
  // },
  // {
  //   identifier: 'erlang',
  //   name: 'Erlang',
  //   color: '#A90533',
  //   icon: 'simple-icons:erlang',
  // },
  // {
  //   identifier: 'fsharp',
  //   name: 'F#',
  //   color: '#B845FC',
  //   icon: 'simple-icons:fsharp',
  // },
  // {
  //   identifier: 'ocaml',
  //   name: 'OCaml',
  //   color: '#EC6813',
  //   icon: 'simple-icons:ocaml',
  // },
  // {
  //   identifier: 'crystal',
  //   name: 'Crystal',
  //   color: '#000100',
  //   icon: 'simple-icons:crystal',
  // },
  // {
  //   identifier: 'nim',
  //   name: 'Nim',
  //   color: '#37775B',
  //   icon: 'simple-icons:nim',
  // },
  // {
  //   identifier: 'coffeescript',
  //   name: 'CoffeeScript',
  //   color: '#2F2625',
  //   icon: 'simple-icons:coffeescript',
  // },
  // {
  //   identifier: 'julia',
  //   name: 'Julia',
  //   color: '#9558B2',
  //   icon: 'simple-icons:julia',
  // },
  // {
  //   identifier: 'matlab',
  //   name: 'MATLAB',
  //   color: '#c04c0b',
  //   icon: 'file-icons:matlab',
  // },
  // {
  //   identifier: 'vba',
  //   name: 'Visual Basic',
  //   color: '#512BD4',
  //   icon: 'simple-icons:visualbasic',
  // },
  // {
  //   identifier: 'fortran',
  //   name: 'Fortran',
  //   color: '#734F96',
  //   icon: 'simple-icons:fortran',
  // },
  // {
  //   identifier: 'assembly',
  //   name: 'Assembly',
  //   color: '#6E4C13',
  //   icon: 'simple-icons:assemblyscript',
  // },
];
